#Get golang 1.22.6 as a base image
FROM golang:1.22.6 as builder

#Define the working directory in the container
WORKDIR /app

#Copy all files from root into the container
COPY . ./

#Use go mod tidy to handle dependencies
RUN go mod tidy

#Run the make task
RUN make wasm
